[package]
name = "wow"
version = "0.0.0"
authors = ["Vladimir Zapparov <dervus.grim@gmail.com>"]

[dependencies]
log = "0.3"
byteorder = "1"
rgb = "0.8"
cgmath = "0.16"

[dev-dependencies]
simplelog = "0.4"